# Generated by Django 2.0.1 on 2018-01-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_1', models.CharField(max_length=64)),
                ('item_2', models.CharField(max_length=64)),
                ('person_1', models.CharField(max_length=64)),
                ('person_2', models.CharField(max_length=64)),
                ('time_created', models.DateTimeField()),
                ('time_mm_received_1', models.DateTimeField(null=True)),
                ('time_mm_received_2', models.DateTimeField(null=True)),
                ('time_mm_completed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='middleman',
            name='bio',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='middleman',
            name='fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='middleman',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='middleman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_manager.Middleman'),
        ),
    ]
