# Generated by Django 2.0.1 on 2018-02-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm_manager', '0003_auto_20180201_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='middleman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mm_manager.Middleman'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='person_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mm_manager.GarlicUser'),
        ),
    ]
