# Generated by Django 2.0.1 on 2018-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_manager', '0004_auto_20180202_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='time_mm_completed',
            new_name='time_completed',
        ),
        migrations.AddField(
            model_name='trade',
            name='time_u1_received',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='time_u2_received',
            field=models.DateTimeField(null=True),
        ),
    ]
