# Generated by Django 2.0.1 on 2018-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_manager', '0005_auto_20180202_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='time_u1_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='time_u2_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='u1_notes',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='u2_notes',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
