# Generated by Django 2.0.1 on 2018-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_manager', '0006_auto_20180202_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='mm_1_notes',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='mm_2_notes',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='time_mm_sent_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='time_mm_sent_2',
            field=models.DateTimeField(null=True),
        ),
    ]
